<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use App\Models\Species;

class SpeciesSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
      //common name / scientific name / family name / order name
      Species::seed('Pari Maekhlong', 'Fluvitrygon kittipongi','Dasyatidae','Myliobatiformes');
      Species::seed('Pari Ketunggau / Pari Sungai / Pari Air Tawar', 'Fluvitrygon signifer','Dasyatidae','Myliobatiformes');
      Species::seed('Belut Gergasi Bengal', 'Anguilla bengalensis','Anguillidae','Anguilliformes');
      Species::seed('Belut gergasi burma', 'Anguilla bicolor','Anguillidae','Anguilliformes');
      Species::seed('Belut Kuning', 'Anguilla marmorata','Anguillidae','Anguilliformes');
      Species::seed('Kelisa', 'Scleropages formosus','Osteoglossidae','Osteoglossiformes');
      Species::seed('Belida', 'Chitala lopis','Notopteridae','Osteoglossiformes');
      Species::seed('Selat', 'Notopterus notopterus','Notopteridae','Osteoglossiformes');
      Species::seed('Bilis Sungai / Tamban Sungai/ Bunga Air/ Renek', 'Clupeichthys perakensis','Clupeidae','Clupeiformes');
      Species::seed('Bilis Khlong Falamee', 'Sundasalanx praecox','Clupeidae','Clupeiformes');
      Species::seed('Lali Nakon sritamarat', 'Syncrossus beauforti','Botiidae','Cypriniformes');
      Species::seed('Lali Babi / Loc Harimau', 'Syncrossus hymenophysa','Botiidae','Cypriniformes');
      Species::seed('Lali Kampuchea', 'Yasuhikotakia morleti','Botiidae','Cypriniformes');
      Species::seed('Belut kecil Kapuas', 'Vaillantella euepiptera','Vaillantellidae','Cypriniformes');
      Species::seed('Belut Kecil Sumatra', 'Vaillantella maassi','Vaillantellidae','Cypriniformes');
      Species::seed('Pasir / Tali / Pasir Jakarta', 'Acantopsis dialuzona','Cobitidae','Cypriniformes');
      Species::seed('Pasir Sarawak', 'Acanthopsoides molobrion','Cobitidae','Cypriniformes');
      Species::seed('Pasir Kapuas', 'Kottelatlimia pristes','Cobitidae','Cypriniformes');
      Species::seed('Pasir Bukit Merah', 'Lepidocephalus furcatus','Cobitidae','Cypriniformes');
      Species::seed('Pasir Jawa', 'Lepidocephalichthys hasselti','Cobitidae','Cypriniformes');
      Species::seed('Pasir Bernam', 'Lepidocephalichthys tomaculum','Cobitidae','Cypriniformes');
      Species::seed('Pasir Palembang', 'Lepidocephalus macrochir','Cobitidae','Cypriniformes');
      Species::seed('Belut Kerdil Terengganu', 'Pangio alcoides','Cobitidae','Cypriniformes');
      Species::seed('Belut Kerdil Kapuas', 'Pangio anguillaris','Cobitidae','Cypriniformes');
      Species::seed('Belut Kerdil Johor', 'Pangio cuneovirgata','Cobitidae','Cypriniformes');
      Species::seed('Belut Kerdil Sarawak', 'Pangio doriae','Cobitidae','Cypriniformes');
      Species::seed('Belut Kerdil Tersat', 'Pangio filinaris','Cobitidae','Cypriniformes');
      Species::seed('Belut Kerdil Malaya', 'Pangio malayana','Cobitidae','Cypriniformes');
      Species::seed('Belut Kerdil Singapura', 'Pangio muraeniformis','Cobitidae','Cypriniformes');
      Species::seed('Belut Kerdil Bogor', 'Pangio oblonga','Cobitidae','Cypriniformes');
      Species::seed('Belut Kerdil Kuala Berang', 'Pangio piperata','Cobitidae','Cypriniformes');
      Species::seed('Belut Kerdil Mawai', 'Pangio semicincta','Cobitidae','Cypriniformes');
      Species::seed('Susur Batu Kalimantan', 'Barbucca diabolica','Barbuccidae','Cypriniformes');
      Species::seed('Puting Beliung Jawa', 'Balitoropsis zollingeri','Balitoridae','Cypriniformes');
      Species::seed('Puting Beliung Negeri Sembilan', 'Homaloptera ogilviei','Balitoridae','Cypriniformes');
      Species::seed('Puting Beliung Sekayu', 'Homaloptera parclitella','Balitoridae','Cypriniformes');
      Species::seed('Puting Beliung Kelantan', 'Homalopteroides nebulosus','Balitoridae','Cypriniformes');
      Species::seed('Puting Beliung Siam', 'Homalopteroides smithi','Balitoridae','Cypriniformes');
      Species::seed('Puting Beliung Mawai', 'Homalopteroides tweediei','Balitoridae','Cypriniformes');
      Species::seed('Puting Beliung Johor', 'Neohomaloptera johorensis','Balitoridae','Cypriniformes');
      Species::seed('Putting Beliung Pahang', 'Pseudohomaloptera leonardi','Balitoridae','Cypriniformes');
      Species::seed('Pasir Sritamarat', 'Nemacheilus masyae','Nemacheilidae','Cypriniformes');
      Species::seed('Pasir Segamat', 'Nemacheilus paucimaculatus','Nemacheilidae','Cypriniformes');
      Species::seed('Pasir Selangor', 'Nemacheilus selangoricus','Nemacheilidae','Cypriniformes');
      Species::seed('Pasir Phuket', 'Paracanthocobitis phuketensis','Nemacheilidae','Cypriniformes');
      Species::seed('Pasir Phangnga', 'Schistura robertsi','Nemacheilidae','Cypriniformes');
      Species::seed('Pasir Tioman', 'Speonectes tiomanensis','Nemacheilidae','Cypriniformes');
      Species::seed('Pasir Chiang Mai', 'Tuberoschistura baenzigeri','Nemacheilidae','Cypriniformes');
      Species::seed('Cypris Sarawak', 'Paedocypris micromegethes','Paedocyprididae','Cypriniformes');
      Species::seed('Mata Besar Kalimantan', 'Amblyrhynchichthys truncatus','Cyprinidae','Cypriniformes');
      Species::seed('Ekor Hangus Banjarmasin', 'Balantiocheilos melanopterus','Cyprinidae','Cypriniformes');
      Species::seed('Batu Ulu Bogor', 'Barbichthys laevis','Cyprinidae','Cypriniformes');
      Species::seed('Tebal sisik Sarawak', 'Barbodes banksi','Cyprinidae','Cypriniformes');
      Species::seed('Tebal sisik Jawa', 'Barbodes binotatus','Cyprinidae','Cypriniformes');
      Species::seed('Baguh Singapura', 'Barbodes dunckeri','Cyprinidae','Cypriniformes');
      Species::seed('Baguh Jawa', 'Barbodes lateristriga','Cyprinidae','Cypriniformes');
      Species::seed('Lampam sungai', 'Barbonymus schwanefeldii','Cyprinidae','Cypriniformes');
      Species::seed('Loket Baram', 'Cosmochilus falcifer','Cyprinidae','Cypriniformes');
      Species::seed('Selimang Padang', 'Crossocheilus cobitis','Cyprinidae','Cypriniformes');
      Species::seed('Selimang Palembang', 'Crossocheilus langei','Cyprinidae','Cypriniformes');
      Species::seed('Selimang Jawa', 'Crossocheilus oblongus','Cyprinidae','Cypriniformes');
      Species::seed('Selimang Sumatra', 'Crossocheilus obscurus','Cyprinidae','Cypriniformes');
      Species::seed('Temperas Sambas', 'Cyclocheilichthys heteronema','Cyprinidae','Cypriniformes');
      Species::seed('Temperas Lampong', 'Cyclocheilichthys repasson','Cyprinidae','Cypriniformes');
      Species::seed('Jalur Sahilan', 'Desmopustius hexazona','Cyprinidae','Cypriniformes');
      Species::seed('Jalur Johor', 'Desmopuntius johorensis','Cyprinidae','Cypriniformes');
      Species::seed('Jalur Baram', 'Desmopuntius pentazona','Cyprinidae','Cypriniformes');
      Species::seed('Tompok Pahang', 'Discherodontus halei','Cyprinidae','Cypriniformes');
      Species::seed('Susur Batang', 'Epalzeorhynchos kalopterum','Cyprinidae','Cypriniformes');
      Species::seed('Selimang Kampuchea', 'Garra cambodgiensis','Cyprinidae','Cypriniformes');
      Species::seed('Sebarau', 'Hampala macrolepidota','Cyprinidae','Cypriniformes');
      Species::seed('Krai Chenderoh', 'Hypsibarbus birtwistlei','Cyprinidae','Cypriniformes');
      Species::seed('Krai Raheng', 'Hypsibarbus malcolmi','Cyprinidae','Cypriniformes');
      Species::seed('Krai Bien Hoa', 'Hypsibarbus pierrei','Cyprinidae','Cypriniformes');
      Species::seed('Krai Chainad', 'Hypsibarbus wetmorei','Cyprinidae','Cypriniformes');
      Species::seed('Jengkua Kalimas', 'Labeo chrysophekadion','Cyprinidae','Cypriniformes');
      Species::seed('Kawan Pengabuang', 'Labiobarbus fasciatus','Cyprinidae','Cypriniformes');
      Species::seed('Kawan Kalimantan', 'Labiobarbus festivus','Cyprinidae','Cypriniformes');
      Species::seed('Kawan Jakarta', 'Labiobarbus leptocheilus','Cyprinidae','Cypriniformes');
      Species::seed('Kawan Indonesia', 'Labiobarbus ocellatus','Cyprinidae','Cypriniformes');
      Species::seed('Jemerung Chieng Mai', 'Lobocheilos rhabdoura','Cyprinidae','Cypriniformes');
      Species::seed('Sia Siam', 'Mystacoleucus chilopterus','Cyprinidae','Cypriniformes');
      Species::seed('Sia Jawa', 'Mystacoleucus obtusirostris','Cyprinidae','Cypriniformes');
      Species::seed('Umbut Banjarmasin', 'Neobarynotus microlepis','Cyprinidae','Cypriniformes');
      Species::seed('Tengas Pulau Pinang', 'Neolissochilus hendersoni','Cyprinidae','Cypriniformes');
      Species::seed('Tengas Bantam', 'Neolissochilus soro','Cyprinidae','Cypriniformes');
      Species::seed('Tengas Pahang', 'Neolissochilus soroides','Cyprinidae','Cypriniformes');
      Species::seed('Rong Tementang', 'Osteochilus flavicauda','Cyprinidae','Cypriniformes');
      Species::seed('Rong Kajahan', 'Osteochilus kahajanensis','Cyprinidae','Cypriniformes');
      Species::seed('Rong Palembang', 'Osteochilus melanopleura','Cyprinidae','Cypriniformes');
      Species::seed('Rong Bantam', 'Osteochilus microcephalus','Cyprinidae','Cypriniformes');
      Species::seed('Rong Trang', 'Osteochilus scapularis','Cyprinidae','Cypriniformes');
      Species::seed('Rong Kalimantan', 'Osteochilus schlegelii','Cyprinidae','Cypriniformes');
      Species::seed('Rong Banjarmasin', 'Osteochilus spilurus','Cyprinidae','Cypriniformes');
      Species::seed('Terbul', 'Osteochilus vittatus','Cyprinidae','Cypriniformes');
      Species::seed('Rong Toboali', 'Osteochilus waandersii','Cyprinidae','Cypriniformes');
      Species::seed('Daun Chantaburi', 'Poropuntius normani','Cyprinidae','Cypriniformes');
      Species::seed('Temoleh', 'Probarbus jullieni','Cyprinidae','Cypriniformes');
      Species::seed('Pelampung Jaring', 'Puntigrus partipentazona','Cyprinidae','Cypriniformes');
      Species::seed('Tengalan', 'Puntioplites bulu','Cyprinidae','Cypriniformes');
      Species::seed('Tengalan Siam', 'Puntioplites proctozysron','Cyprinidae','Cypriniformes');
      Species::seed('Tebal sisik indonesia', 'Puntius brevis','Cyprinidae','Cypriniformes');
      Species::seed('Jalur Muar', 'Striuntius lineatus','Cyprinidae','Cypriniformes');
      
      Species::seed('Pipi Merah', 'Systomus rubripinnis','Cyprinidae','Cypriniformes');
      Species::seed('Loma', 'Thynnichthys thynnoides','Cyprinidae','Cypriniformes');
      Species::seed('Kelah', 'Tor tambra','Cyprinidae','Cypriniformes');
      Species::seed('Seluang Muar', 'Boraras maculatus','Danionidae','Cypriniformes');
      Species::seed('Seluang Terengganu', 'Brevibora cheeya','Danionidae','Cypriniformes');
      Species::seed('Seluang Jelai', 'Brevibora dorsiocellata','Danionidae','Cypriniformes');
      Species::seed('Seluang Pelangi/ Ratu/ Kepiat/ Bada Pelangi', 'Devario regina','Danionidae','Cypriniformes');
      Species::seed('Barb Terbang Malaya', 'Esomus malayensis','Danionidae','Cypriniformes');
      Species::seed('Barb Terbang Jalur', 'Esomus metallicus','Danionidae','Cypriniformes');
      Species::seed('Pin-pin Siam', 'Laubuka siamensis','Danionidae','Cypriniformes');
      Species::seed('Seluang / Bada/ Nyelua/ Nyuar', 'Luciosoma setigerum','Danionidae','Cypriniformes');
      Species::seed('Juajo/ Nyenyuar Palembang', 'Luciosoma trinema','Danionidae','Cypriniformes');
      Species::seed('Pin-pin Kampar', 'Malayochela maassi','Danionidae','Cypriniformes');
      Species::seed('Sikang', 'Raiamas guttatus','Danionidae','Cypriniformes');
      Species::seed('Seluang / Susur Batang / Seluang Bangka', 'Rasbora bankanensis','Danionidae','Cypriniformes');
      Species::seed('Seluang Ekor Hangus / Seluang Semangus', 'Rasbora caudimaculata','Danionidae','Cypriniformes');
      Species::seed('Seluang Cirucup', 'Rasbora cephalotaenia','Danionidae','Cypriniformes');
      Species::seed('Seluang Duson', 'Rasbora dusonensis','Danionidae','Cypriniformes');
      Species::seed('Seluang Sambas', 'Rasbora einthovenii','Danionidae','Cypriniformes');
      Species::seed('Sluang / Susur Batang / Seluang Tompok', 'Rasbora elegans','Danionidae','Cypriniformes');
      Species::seed('Seluang / Seluang Putussibau', 'Rasbora myersi','Danionidae','Cypriniformes');
      Species::seed('Seluang / Seluang Johor', 'Rasbora paucisqualis','Danionidae','Cypriniformes');
      Species::seed('Seluang Gadang', 'Rasbora tornieri','Danionidae','Cypriniformes');
      Species::seed('Seluang bada', 'Rasbora trilineata','Danionidae','Cypriniformes');
      Species::seed('Seluang Badar', 'Trigonopoma gracile','Danionidae','Cypriniformes');
      Species::seed('Seluang Sahilan', 'Trigonopoma pauciperforatum','Danionidae','Cypriniformes');
      Species::seed('Seluang Semenyih', 'Trigonostigma heteromorpha','Danionidae','Cypriniformes');
      Species::seed('Jelawat', 'Leptobarbus hoevenii','Leptobarbidae','Cypriniformes');
      Species::seed('Parang Sungai', 'Macrochirichthys macrochirus','Xenocyprididae','Cypriniformes');
      Species::seed('Lalang / Bulu Ayam', 'Oxygaster anomalura','Xenocyprididae','Cypriniformes');
      Species::seed('Riu Yunan', 'Clupisoma sinense','Ailiidae','Siluriformes');
      Species::seed('Riu Palembang', 'Laides hexanema','Schilbeidae','Siluriformes');
      Species::seed('Keli Katak bangka', 'Chaca bankanensis','Chacidae','Siluriformes');
      Species::seed('Baung Tikus Lamatang', 'Bagrichthys macracanthus','Bagridae','Siluriformes');
      Species::seed('Baung Sungai', 'Hemibagrus capitulum','Bagridae','Siluriformes');
      Species::seed('Baung Besar Perak', 'Hemibagrus divaricatus','Bagridae','Siluriformes');
      Species::seed('Baung Besar Johor', 'Hemibagrus gracilis','Bagridae','Siluriformes');
      Species::seed('Baung Besar Kepong', 'Hemibagrus hoevenii','Bagridae','Siluriformes');
      Species::seed('Baung Kelulang', 'Hemibagrus wyckii','Bagridae','Siluriformes');
      Species::seed('Baung Kecil Muar', 'Hyalobagrus ornatus','Bagridae','Siluriformes');
      Species::seed('Baung Kecil Cirucup', 'Leiocassis micropogon','Bagridae','Siluriformes');
      Species::seed('Baung Kecil Hebak', 'Leiocassis poeciloptera','Bagridae','Siluriformes');
      Species::seed('Baung Kecil Indragiri', 'Mystus bimaculatus','Bagridae','Siluriformes');
      Species::seed('Baung Kecil Sadong', 'Mystus castaneus','Bagridae','Siluriformes');
      Species::seed('Baung Kecil Ganges', 'Mystus gulio','Bagridae','Siluriformes');
      Species::seed('Baung Kecil Jawa', 'Mystus singaringan','Bagridae','Siluriformes');
      Species::seed('Baung Kecil Kalimantan', 'Mystus wolffii','Bagridae','Siluriformes');
      Species::seed('Baung Kerdil Terengganu', 'Nanobagrus lemniscatus','Bagridae','Siluriformes');
      Species::seed('Baung Kerdil Kahang', 'Nanobagrus nebulosus','Bagridae','Siluriformes');
      Species::seed('Baung Kerdil Jambi', 'Nanobagrus stellatus','Bagridae','Siluriformes');
      Species::seed('Baung Kerdil Musi', 'Nanobagrus torquatus','Bagridae','Siluriformes');
      Species::seed('Baung Kerdil Kuala Tahan', 'Pseudomystus fumosus','Bagridae','Siluriformes');
      Species::seed('Baung Kecil Kuantan', 'Pseudomystus leiacanthus','Bagridae','Siluriformes');
      Species::seed('Baung Kecil Indonesia', 'Pseudomystus stenomus','Bagridae','Siluriformes');
      Species::seed('Depu Surakarta', 'Acrochordonichthys rugosus','Akysidae','Siluriformes');
      Species::seed('Depu Kanchanaburi', 'Acrochordonichthys septentrionalis','Akysidae','Siluriformes');
      Species::seed('Depu Terengganu', 'Akysis hendricksoni','Akysidae','Siluriformes');
      Species::seed('Depu Kahang', 'Akysis microps','Akysidae','Siluriformes');
      Species::seed('Depu Singapura', 'Parakysis longirostris','Akysidae','Siluriformes');
      Species::seed('Depu Mawai', 'Parakysis verrucosus','Akysidae','Siluriformes');
      Species::seed('Depu Pahang', 'Pseudobagarius alfredi','Akysidae','Siluriformes');
      Species::seed('Keli Kecil Berang', 'Amblyceps foratum','Amblycipitidae','Siluriformes');
      Species::seed('Kenerak', 'Bagarius yarrelli','Sisoridae','Siluriformes');
      Species::seed('Kenerak Kerdil Chantaburi', 'Glyptothorax fuscus','Sisoridae','Siluriformes');
      Species::seed('Kenerak Kerdil Lahat', 'Glyptothorax platypogonides','Sisoridae','Siluriformes');
      Species::seed('Kenerak Kerdil Simbolon', 'Glyptothorax schmidti','Sisoridae','Siluriformes');
      Species::seed('Patin Muncung Sumatra', 'Helicophagus waandersii','Pangasiidae','Siluriformes');
      Species::seed('Patin Kalimantan', 'Pangasius nasutus','Pangasiidae','Siluriformes');
      Species::seed('Patin Banjarmasin', 'Pangasius polyuranodon','Pangasiidae','Siluriformes');
      Species::seed('Patin Juara Solo', 'Pseudolais micronemus','Pangasiidae','Siluriformes');
      Species::seed('Gerahak Banjarmasin', 'Belodontichthys dinema','Siluridae','Siluriformes');
      Species::seed('Bilut Jawa', 'Ceratoglanis scleronema','Siluridae','Siluriformes');
      Species::seed('Lais Jawa', 'Kryptopterus bicirrhis','Siluridae','Siluriformes');
      Species::seed('Lais Banjarmasin', 'Kryptopterus cryptopterus','Siluridae','Siluriformes');
      Species::seed('Lais Sumatra', 'Kryptopterus limpok','Siluridae','Siluriformes');
      Species::seed('Lais Padang', 'Kryptopterus macrocephalus','Siluridae','Siluriformes');
      Species::seed('Lais Palembang', 'Kryptopterus palembangensis','Siluridae','Siluriformes');
      Species::seed('Lais Siam', 'Kryptopterus vitreolus','Siluridae','Siluriformes');
      Species::seed('Lais Kalimantan', 'Ompok eugeneiatus','Siluridae','Siluriformes');
      Species::seed('Lais Selangor', 'Ompok fumidus','Siluridae','Siluriformes');
      Species::seed('Lais Karang', 'Ompok rhadinurus','Siluridae','Siluriformes');
      Species::seed('Lais Indonesia', 'Ompok siluroides','Siluridae','Siluriformes');
      Species::seed('Segahak Kalimantan', 'Phalacronotus apogon','Siluridae','Siluriformes');
      Species::seed('Tapah Bemban Jawa', 'Silurichthys hasseltii','Siluridae','Siluriformes');
      Species::seed('Tapah Bemban Indragiri', 'Silurichthys indragiriensis','Siluridae','Siluriformes');
      Species::seed('Tapah Bemban Sumatra', 'Silurichthys schneideri','Siluridae','Siluriformes');
      Species::seed('Tapah Gergasi', 'Wallagonia leerii Bleeker','Siluridae','Siluriformes');
      Species::seed('Keli Bandung', 'Clarias batrachus','Clariidae','Siluriformes');
      Species::seed('Keli Tioman', 'Clarias batu','Clariidae','Siluriformes');
      Species::seed('Keli Sambas', 'Clarias leiacanthus','Clariidae','Siluriformes');
      Species::seed('Keli Siam', 'Clarias macrocephalus','Clariidae','Siluriformes');
      Species::seed('Keli Jakarta', 'Clarias meladerma','Clariidae','Siluriformes');
      Species::seed('Keli Asia', 'Clarias nieuhofii','Clariidae','Siluriformes');
      Species::seed('Keli Redang', 'Clarias sulcatus','Clariidae','Siluriformes');
      Species::seed('Keli Kerdi Selangor', 'Encheloclarias curtisoma','Clariidae','Siluriformes');
      Species::seed('Keli Kerdil Kuantan', 'Encheloclarias kelioides','Clariidae','Siluriformes');
      Species::seed('Ranting Banjar Masin', 'Doryichthys boaja','Syngnathidae','Siluriformes');
      Species::seed('Ranting Palembang', 'Doryichthys deokhatoides','Syngnathidae','Siluriformes');
      Species::seed('Ranting Kalimantan', 'Doryichthys martensii','Syngnathidae','Siluriformes');
      Species::seed('Ketutu Banjarmasin', 'Oxyeleotris marmorata','Eleotridae','Siluriformes');
      Species::seed('Gobi Mawai', 'Brachygobius xanthomelas','Gobiidae','Siluriformes');
      Species::seed('Gobi Siam', 'Eugnathogobius siamensis','Gobiidae','Siluriformes');
      Species::seed('Gobi Ambon', 'Pseudogobiopsis oligactis','Gobiidae','Siluriformes');
      Species::seed('Gobi Kota Tinggi', 'Pseudogobiopsis paludosa','Gobiidae','Siluriformes');
      Species::seed('Tilan Patalung', 'Macrognathus circumcinctus','Mastacembelidae','Siluriformes');
      Species::seed('Tilan Moluccas', 'Macrognathus maculatus','Mastacembelidae','Siluriformes');
      Species::seed('Tilan Siam', 'Macrognathus tapirus','Mastacembelidae','Siluriformes');
      Species::seed('Tilan Banjarmasin', 'Mastacembelus erythrotaenia','Mastacembelidae','Siluriformes');
      Species::seed('Tilan Tale Sap', 'Mastacembelus favus','Mastacembelidae','Siluriformes');
      Species::seed('Tilan Perak', 'Mastacembelus notophthalmus','Mastacembelidae','Siluriformes');
      Species::seed('Tilan Myanmar', 'Mastacembelus tinwini','Mastacembelidae','Siluriformes');
      Species::seed('Tilan Jawa', 'Mastacembelus unicolor','Mastacembelidae','Siluriformes');
      Species::seed('Naga Tanjung Malim', 'Bihunichthys monopteroides','Chaudhuriidae','Siluriformes');
      Species::seed('Naga Myanmar', 'Chaudhuria caudata','Chaudhuriidae','Siluriformes');
      Species::seed('Naga Rawang', 'Chendol keelini','Chaudhuriidae','Siluriformes');
      Species::seed('Naga Pinyuh', 'Nagaichthys filipes','Chaudhuriidae','Siluriformes');
      Species::seed('Ranting Narathiwat', 'Indostomus crocodilus','Indostomatidae','Siluriformes');
      Species::seed('Belut Jawa', 'Monopterus javanensis','Synbranchidae','Siluriformes');
      Species::seed('Puyu', 'Anabas testudineus','Anabantidae','Anabantiformes');
      Species::seed('Temakang Jawa', 'Helostoma temminckii','Helostomatidae','Anabantiformes');
      Species::seed('Kepar Jawa', 'Belontia hasselti','Osphronemidae','Anabantiformes');
      Species::seed('Laga Narathiwat', 'Betta apollon','Osphronemidae','Anabantiformes');
      Species::seed('Laga Bernam', 'Betta bellica','Osphronemidae','Anabantiformes');
      Species::seed('Laga Jambi', 'Betta coccina','Osphronemidae','Anabantiformes');
      Species::seed('Laga Tanjung Malim', 'Betta hipposideros','Osphronemidae','Anabantiformes');
      Species::seed('Laga Kuala Lumpur', 'Betta imbellis','Osphronemidae','Anabantiformes');
      Species::seed('Laga Kota Bharu', 'Betta kuehnei','Osphronemidae','Anabantiformes');
      Species::seed('Laga Sungai Besar', 'Betta livida','Osphronemidae','Anabantiformes');
      Species::seed('Laga Pekan Nenas', 'Betta omega','Osphronemidae','Anabantiformes');
      Species::seed('Laga Ayer Hitam', 'Betta persephone','Osphronemidae','Anabantiformes');
      Species::seed('Laga Tod Deng', 'Betta pi','Osphronemidae','Anabantiformes');
      Species::seed('Laga Pulau Pinang', 'Betta pugnax','Osphronemidae','Anabantiformes');
      Species::seed('Laga Pontian', 'Betta pulchra','Osphronemidae','Anabantiformes');
      Species::seed('Laga Sekayu', 'Betta stigmosa','Osphronemidae','Anabantiformes');
      Species::seed('Laga Mupor', 'Betta tomi','Osphronemidae','Anabantiformes');
      Species::seed('Laga Pahang', 'Betta tussyae','Osphronemidae','Anabantiformes');
      Species::seed('Laga Kuantan', 'Betta waseri','Osphronemidae','Anabantiformes');
      Species::seed('Tembok Tebing Malaya', 'Luciocephalus pulcher','Osphronemidae','Anabantiformes');
      Species::seed('Kaloi Indonesia', 'Osphronemus goramy','Osphronemidae','Anabantiformes');
      Species::seed('Gorami Kecil Mawai', 'Parosphromenus alfredi','Osphronemidae','Anabantiformes');
      Species::seed('Gorami Kecil Selangor', 'Parosphromenus harveyi','Osphronemidae','Anabantiformes');
      Species::seed('Gorami Kecil Kuantan', 'Parosphromenus nagyi','Osphronemidae','Anabantiformes');
      Species::seed('Gorami Kecil Terengganu', 'Parosphromenus paludicola','Osphronemidae','Anabantiformes');
      Species::seed('Gorami Kecila Beriah', 'Parosphromenus rubrimontis','Osphronemidae','Anabantiformes');
      Species::seed('Gorami Kecil Pontian', 'Parosphromenus tweediei','Osphronemidae','Anabantiformes');
      Species::seed('Gorami Coklat Indonesia', 'Sphaerichthys osphromenoides','Osphronemidae','Anabantiformes');
      Species::seed('Sepat Palembang', 'Trichopodus leerii','Osphronemidae','Anabantiformes');
      Species::seed('Sepat Siam', 'Trichopodus pectoralis','Osphronemidae','Anabantiformes');
      Species::seed('Sepat Indonesia', 'Trichopodus trichopterus','Osphronemidae','Anabantiformes');
      Species::seed('Karim Jawa', 'Trichopsis vittata','Osphronemidae','Anabantiformes');
      Species::seed('Bujuk Bangka', 'Channa bankanensis','Channidae','Anabantiformes');
      Species::seed('Haruan Jawa', 'Channa limbata','Channidae','Anabantiformes');
      Species::seed('Bujuk Jawa', 'Channa lucius','Channidae','Anabantiformes');
      Species::seed('Toman Kalimantan', 'Channa marulioides','Channidae','Anabantiformes');
      Species::seed('Haruan Sambas', 'Channa melasoma','Channidae','Anabantiformes');
      Species::seed('Toman Jawa', 'Channa micropeltes','Channidae','Anabantiformes');
      Species::seed('Haruan Tharangambadi', 'Channa striata','Channidae','Anabantiformes');
      Species::seed('Daun Kering Indonesia', 'Nandus nebolusus','Nandidae','Anabantiformes');
      Species::seed('Patung Banjarmasin', 'Pristolepis fasciata','Pristolepididae','Anabantiformes');
      Species::seed('Patung Belitung', 'Pristolepis grootii','Pristolepididae','Anabantiformes');
      Species::seed('Sebelah Surakarta', 'Achiroides leucorhynchos','Soleidae','Pleuronectiformes');
      Species::seed('Sebelah Banjarmasin', 'Achiroides melanorhynchus','Soleidae','Pleuronectiformes');
      Species::seed('Todak Kapuas', 'Xenentodon canciloides','Belonidae','Beloniformes');
      Species::seed('Jolong-jolong Sarawak', 'Dermogenys collettei','Zenarchopteridae','Beloniformes');
      Species::seed('Jolong-jolong Marawang', 'Hemirhamphodon pogonognathus','Zenarchopteridae','Beloniformes');
      Species::seed('Buntal Banjarmasin', 'Auriglobus modestus','Tetraodontidae','Tetraodontiformes');
      Species::seed('Buntal Putussibau', 'Auriglobus nefastus','Tetraodontidae','Tetraodontiformes');
      Species::seed('Buntal Jakarta', 'Pao leiurus','Tetraodontidae','Tetraodontiformes');
      Species::seed('Buntal Palembang', 'Pao palembangensis','Tetraodontidae','Tetraodontiformes');
      Species::seed('Gelas Banjarmasin', 'Parambassis apogonoides','Ambassidae','Perciformes');
      Species::seed('Gelas Siam', 'Parambassis siamensis','Ambassidae','Perciformes');
      
    }
}